<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfe9995aa8c1a4fa5c8608331a1edfdd8
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfe9995aa8c1a4fa5c8608331a1edfdd8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfe9995aa8c1a4fa5c8608331a1edfdd8::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitfe9995aa8c1a4fa5c8608331a1edfdd8::$classMap;

        }, null, ClassLoader::class);
    }
}
